import { TextureFormat } from "@feng3d/render-api";
import { IGLTextureFormats } from "../data/IGLTextureFormats";

export function getIGLTextureFormats(format: TextureFormat = "rgba8unorm")
{
    const glTextureFormat: IGLTextureFormats = formatMap[format];

    console.assert(!!glTextureFormat, `未处理格式 ${format}；或者WebGL不支持纹理， 该格式只在WebGPU中支持！`);

    return glTextureFormat;
}

const formatMap: { [key: string]: IGLTextureFormats } = {
    r8unorm: { internalformat: "R8", format: "RED", type: "UNSIGNED_BYTE" },
    r8snorm: undefined,
    r8uint: { internalformat: "R8", format: "RED", type: "UNSIGNED_BYTE" },
    r8sint: undefined,
    r16uint: undefined,
    r16sint: undefined,
    r16float: { internalformat: "R16F", format: "RED", type: "HALF_FLOAT" },
    rg8unorm: undefined,
    rg8snorm: undefined,
    rg8uint: undefined,
    rg8sint: undefined,
    r32uint: undefined,
    r32sint: undefined,
    r32float: undefined,
    rg16uint: undefined,
    rg16sint: undefined,
    rg16float: { internalformat: "RG16F", format: "RG", type: "HALF_FLOAT" },
    rgba8unorm: { internalformat: "RGBA8", format: "RGBA", type: "UNSIGNED_BYTE" },
    "rgba8unorm-srgb": { internalformat: "SRGB8", format: "RGB", type: "UNSIGNED_BYTE" },
    rgba8snorm: undefined,
    rgba8uint: { internalformat: "RGBA8UI", format: "RGBA_INTEGER", type: "UNSIGNED_BYTE" },
    rgba8sint: undefined,
    bgra8unorm: undefined,
    "bgra8unorm-srgb": undefined,
    rgb9e5ufloat: undefined,
    rgb10a2uint: undefined,
    rgb10a2unorm: undefined,
    rg11b10ufloat: undefined,
    rg32uint: undefined,
    rg32sint: undefined,
    rg32float: undefined,
    rgba16uint: undefined,
    rgba16sint: undefined,
    rgba16float: { internalformat: "RGB16F", format: "RGB", type: "HALF_FLOAT" },
    rgba32uint: undefined,
    rgba32sint: undefined,
    rgba32float: { internalformat: "RGBA32F", format: "RGBA", type: "FLOAT" },
    stencil8: undefined,
    depth16unorm: { internalformat: "DEPTH_COMPONENT16", format: "DEPTH_COMPONENT", type: "UNSIGNED_SHORT" },
    depth24plus: undefined,
    "depth24plus-stencil8": undefined,
    depth32float: undefined,
    "depth32float-stencil8": undefined,
    "bc1-rgba-unorm": undefined,
    "bc1-rgba-unorm-srgb": undefined,
    "bc2-rgba-unorm": undefined,
    "bc2-rgba-unorm-srgb": undefined,
    "bc3-rgba-unorm": undefined,
    "bc3-rgba-unorm-srgb": undefined,
    "bc4-r-unorm": undefined,
    "bc4-r-snorm": undefined,
    "bc5-rg-unorm": undefined,
    "bc5-rg-snorm": undefined,
    "bc6h-rgb-ufloat": undefined,
    "bc6h-rgb-float": undefined,
    "bc7-rgba-unorm": undefined,
    "bc7-rgba-unorm-srgb": undefined,
    "etc2-rgb8unorm": undefined,
    "etc2-rgb8unorm-srgb": undefined,
    "etc2-rgb8a1unorm": undefined,
    "etc2-rgb8a1unorm-srgb": undefined,
    "etc2-rgba8unorm": undefined,
    "etc2-rgba8unorm-srgb": undefined,
    "eac-r11unorm": undefined,
    "eac-r11snorm": undefined,
    "eac-rg11unorm": undefined,
    "eac-rg11snorm": undefined,
    "astc-4x4-unorm": undefined,
    "astc-4x4-unorm-srgb": undefined,
    "astc-5x4-unorm": undefined,
    "astc-5x4-unorm-srgb": undefined,
    "astc-5x5-unorm": undefined,
    "astc-5x5-unorm-srgb": undefined,
    "astc-6x5-unorm": undefined,
    "astc-6x5-unorm-srgb": undefined,
    "astc-6x6-unorm": undefined,
    "astc-6x6-unorm-srgb": undefined,
    "astc-8x5-unorm": undefined,
    "astc-8x5-unorm-srgb": undefined,
    "astc-8x6-unorm": undefined,
    "astc-8x6-unorm-srgb": undefined,
    "astc-8x8-unorm": undefined,
    "astc-8x8-unorm-srgb": undefined,
    "astc-10x5-unorm": undefined,
    "astc-10x5-unorm-srgb": undefined,
    "astc-10x6-unorm": undefined,
    "astc-10x6-unorm-srgb": undefined,
    "astc-10x8-unorm": undefined,
    "astc-10x8-unorm-srgb": undefined,
    "astc-10x10-unorm": undefined,
    "astc-10x10-unorm-srgb": undefined,
    "astc-12x10-unorm": undefined,
    "astc-12x10-unorm-srgb": undefined,
    "astc-12x12-unorm": undefined,
    "astc-12x12-unorm-srgb": undefined,
};