name: tests
on:
  push:
  pull_request:
    branches: [ $default-branch ]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Clean pnpm cache
        run: npm cache clean
      - uses: npm/action-setup@v2.2.1 # 尝试更换版本
        with:
          version: latest
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: 'npm'
      - name: Install dependencies
        run: npm i --no-frozen-lockfile
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
